#!/usr/bin/env bash
# Builds the distributable artifacts:
#   dist/PROMPT.md              -> single file, paste into any LLM
#   dist/super-mkt.zip  -> Agent Skill package (SKILL.md + references/)
set -euo pipefail

cd "$(dirname "$0")"
SRC=skills/super-mkt
OUT=dist
NAME=super-mkt

rm -rf "$OUT"
mkdir -p "$OUT"

# --- 1. single-file bundle ---------------------------------------------------
{
  echo "<!-- Generated by build.sh. Do not edit: edit $SRC/SKILL.md and $SRC/references/*.md -->"
  echo
  # SKILL.md without the YAML frontmatter; reference pointers become appendix pointers
  awk 'BEGIN{f=0} /^---$/{f++; next} f>=2' "$SRC/SKILL.md" \
    | sed 's|`references/\([a-z]*\)\.md`|the `references/\1.md` appendix at the end of this document|g'
  for f in frameworks formats briefing; do
    echo
    echo "---"
    echo
    echo "# Appendix: references/$f.md"
    echo
    # demote every heading one level so it nests under the appendix title
    sed 's/^#/##/' "$SRC/references/$f.md"
  done
} > "$OUT/PROMPT.md"

# --- 2. Agent Skill zip ------------------------------------------------------
cp README.md LICENSE "$SRC/" 2>/dev/null || true
(cd skills && zip -qr "../$OUT/$NAME.zip" super-mkt -x "*.DS_Store")
rm -f "$SRC/README.md" "$SRC/LICENSE"

printf 'ok:\n  %s (%s bytes)\n  %s (%s bytes)\n' \
  "$OUT/PROMPT.md" "$(wc -c < "$OUT/PROMPT.md" | tr -d ' ')" \
  "$OUT/$NAME.zip" "$(wc -c < "$OUT/$NAME.zip" | tr -d ' ')"
